### DISCUSSION TITLE
CSS for styling

### DISCUSSION THREAD

**Discussion by VisenDev** [david-vanderson/dvui#148] [Ideas]
Related #133

I think it might be interesting to experiment with using CSS for styling. CSS is fairly simple and standardized, so it should be intuitive for most people. I got this idea seeing how [waybar](https://github.com/Alexays/Waybar) uses css for its styling and how simple that was. 

I'm not sure I'm completely happy with the new situation of using `QuickTheme` and `Theme` to decide styles, so here are some alternative thoughts for what CSS styling implementation might look like. 

- `dvui.Options` would be given `css_id: []const u8` and `css_class: []const u8` fields
- Child widgets would inherit styling rules from their parents unless overriddened
- Concept of what a CSS Style type might look like
    ```zig
    const CssStyle = struct {
       @"font-family": [][]const u8,
       @"font-size",
       color: [7]u8,
       background-color: [7]u8,
       //other standard css options here
    }
    ```
   - When rendering, widgets would query the "global dvui css state" with all the information about the current widget, such as css-class, css-id, parent widgets, hovered status, clicked status, etc... Then css state would then use these css selectors to determine how that widget should be rendered. 
   
   
 Example of the jungle theme might look implemented in css
 
 ```css
 body {
   font-size: 18;
   font-family: pixelify;
}

heading {
   /* Heading font-size will be 75% of body's font-size*/
   font-size: 75%; 
}

caption {
    /* Caption font-size will be 75% of body's font-size*/
   font-size: 75%; 
}

title {
    font-size: 150%;
}

text {
    color: #82a29f,
    background-color: #2c3332,
}

text:active {
   /* Pressed text styling here*/
}

container:hover {
   /* hovered styling here*/
}

/*etc...*/
```
